version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: proj
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  web:
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

volumes:
  db_data: